name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        redis-version: [3, 4, 5, 6]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Run Tox
        run: CI=true tox
      - name: Upload coverage.xml
        if: ${{ matrix.redis-version == '5' && matrix.python-version == '3.9' }}
        uses: actions/upload-artifact@v2
        with:
          name: rom-coverage
          path: coverage.xml
          if-no-files-found: error
      - name: Codecov
        if: ${{ matrix.redis-version == '5' && matrix.python-version == '3.9' }}
        uses: codecov/codecov-action@v2.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          env_vars: OS,PYTHON
